# 第3回 練習問題 解答

In [1]:
# 以下のライブラリを使うので、あらかじめ読み込んでおいてください
import numpy as np

%matplotlib inline

# 小数第３まで表示
%precision 3

'%.3f'

### 1.3 練習問題

**問1** \
(1) 1次元であなたの好きな値を要素にもつ同じ長さの`np.ndarray`を2つ作成し、`type()`関数を用いて`np.ndarray`になっていることを確認してください。\
(2) (1)で作成した2つの1次元配列に対して要素ごとの四則演算を行ってください。

In [ ]:
#(1)
array1 =  np.array([1,2,3,4,5])
array2 =  np.array([6,7,8,9,10])

In [ ]:
type(array1)

numpy.ndarray

In [ ]:
type(array2)

numpy.ndarray

In [ ]:
#(2)
print('加法',array1 + array2)
print('減法',array1 - array2)
print('乗法',array1 * array2)
print('除法',array1 / array2)

加法 [ 7  9 11 13 15]
減法 [-5 -5 -5 -5 -5]
乗法 [ 6 14 24 36 50]
除法 [0.167 0.286 0.375 0.444 0.5  ]


**問２**\
1次元配列を入力とし、その配列をL2ノルムで規格化した配列を出力する関数を作成してください。

ここで、ベクトルのL2ノルムによる規格化とは、元のベクトルと同じ向きで、長さ（L2ノルム、つまり全要素の2乗和の平方根）が1になるようにスカラー倍することです。

このとき、NumPyの**ユニバーサル関数や基本的な演算のみ**を用いて実装してください。

In [ ]:
def normalize(a):
    return a/np.sqrt(np.sum(a**2))

In [ ]:
array1

array([1, 2, 3, 4, 5])

In [ ]:
print(normalize(array1))
print(np.sqrt(np.sum(normalize(array1)**2)))

[0.135 0.27  0.405 0.539 0.674]
1.0


### 2.4練習問題

**問1** インデキシングの基礎\
あなたが作成した任意の配列に対して，前から一番目と後ろから一番目の値を取得して表示してください。

In [ ]:
a = np.array([1,2,3,4,5])
print("前から一番目の値:",a[0])
print("後ろから一番目の値:",a[-1])

前から一番目の値: 1
後ろから一番目の値: 5


**問2** ブールインデックス参照 \
(1) 整数値を要素にもつNumPyの1次元配列を引数として、その配列の中から、要素が奇数であるか、または4で割って2余る数である要素のみを抽出した新しい配列を出力する関数を実装してください。\
(2) 正の整数`n`を引数として、`n`より小さい正の平方数の個数を、ブールインデックス参照を用いて求める関数を実装してください(ヒント:十分な数の正の平方数を小さい順に列挙し，その中で引数より小さいものを数える)。

In [ ]:
# (1)
def make_bool_ids(a):
    idx1 = (a % 2 != 0)
    idx2 = (a % 4 == 2)
    idx = idx1 | idx2
    return a[idx]

In [ ]:
# 入力例
a = np.array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5])
print(make_bool_ids(a))
# 出力例
# np.array([1, 1, 2, 2, 3, 3, 5, 5])

[1 1 2 2 3 3 5 5]


In [ ]:
# (2)
def count_square(n):
    array = np.arange(1,n) ** 2
    answer = np.sum((array < n))
    return answer

In [ ]:
# (2)別解
def count_square(n):
    array = np.arange(1,n)
    answer = np.sum((array < np.sqrt(n)))
    return answer

In [ ]:
# 入力例
n = 20
answer = count_square(n)
print(answer)
# 出力例
# 20未満の正の平方数は1, 4, 9, 16
# 4

4


### 3.4 練習問題

**問1**
(1) 5人の生徒の4回分のテスト結果（100点満点）を要素とするNumPy 2次元配列を作成してください。\
このとき、axis 0を生徒でaxis 1をテストの各回だとします。また、値は任意であるとします。

(2) それぞれの生徒の4回分のテスト結果の最高点・最低点・平均・分散をそれぞれ計算してください。\
その結果を、`axis 0`が生徒、`axis 1`が集約結果（最高点、最低点、平均、分散の順）となる`shape=(5, 4)`の2次元配列にしてください。

(3) 各テストの点数について、その点数とその生徒の平均点との差の絶対値を計算し、`shape=(5, 4)`の2次元配列としてください。

In [ ]:
# (1)
array = np.array([[90, 100, 80, 56],
                    [67, 94, 29, 90],
                    [94, 56, 92, 74],
                    [39, 46, 62, 74],
                    [23, 48, 81, 83]
                    ])

In [ ]:
# (2)
print('student1',
      f'最高点:{np.max(array, axis=1)[0]}',
      f'最低点:{np.min(array, axis=1)[0]}',
      f'平均点:{np.mean(array, axis=1)[0]}',
      f'分散:{np.var(array, axis=1)[0]}')

print('student2',
      f'最高点:{np.max(array, axis=1)[1]}',
      f'最低点:{np.min(array, axis=1)[1]}',
      f'平均点:{np.mean(array, axis=1)[1]}',
      f'分散:{np.var(array, axis=1)[1]}')

print('studet3',
      f'最高点:{np.max(array, axis=1)[2]}',
      f'最低点:{np.min(array, axis=1)[2]}',
      f'平均点:{np.mean(array, axis=1)[2]}',
      f'分散:{np.var(array, axis=1)[2]}')

print('student4',
      f'最高点:{np.max(array, axis=1)[3]}',
      f'最低点:{np.min(array, axis=1)[3]}',
      f'平均点:{np.mean(array, axis=1)[3]}',
      f'分散:{np.var(array, axis=1)[3]}')

print('student5',
      f'最高点:{np.max(array, axis=1)[4]}',
      f'最低点:{np.min(array, axis=1)[4]}',
      f'平均点:{np.mean(array, axis=1)[4]}',
      f'分散:{np.var(array, axis=1)[4]}')

array2 = np.array(
    [
        [np.max(array, axis=1)[0],np.min(array, axis=1)[0],np.mean(array, axis=1)[0],np.var(array, axis=1)[0]],
        [np.max(array, axis=1)[1],np.min(array, axis=1)[1],np.mean(array, axis=1)[1],np.var(array, axis=1)[1]],
        [np.max(array, axis=1)[2],np.min(array, axis=1)[2],np.mean(array, axis=1)[2],np.var(array, axis=1)[2]],
        [np.max(array, axis=1)[3],np.min(array, axis=1)[3],np.mean(array, axis=1)[3],np.var(array, axis=1)[3]],
        [np.max(array, axis=1)[4],np.min(array, axis=1)[4],np.mean(array, axis=1)[4],np.var(array, axis=1)[4]],
    ]
)

student1 最高点:100 最低点:56 平均点:81.5 分散:266.75
student2 最高点:94 最低点:29 平均点:70.0 分散:666.5
studet3 最高点:94 最低点:56 平均点:79.0 分散:237.0
student4 最高点:74 最低点:39 平均点:55.25 分散:186.6875
student5 最高点:83 最低点:23 平均点:58.75 分散:619.1875


In [ ]:
array2

array([[100.   ,  56.   ,  81.5  , 266.75 ],
       [ 94.   ,  29.   ,  70.   , 666.5  ],
       [ 94.   ,  56.   ,  79.   , 237.   ],
       [ 74.   ,  39.   ,  55.25 , 186.688],
       [ 83.   ,  23.   ,  58.75 , 619.188]])

In [ ]:
array2[:,2].reshape(5,1)

array([[81.5 ],
       [70.  ],
       [79.  ],
       [55.25],
       [58.75]])

In [ ]:
# (3)
array3 = np.abs(array-array2[:,2].reshape(5,1))

In [ ]:
print(array3)
print(array3.shape)

[[ 8.5  18.5   1.5  25.5 ]
 [ 3.   24.   41.   20.  ]
 [15.   23.   13.    5.  ]
 [16.25  9.25  6.75 18.75]
 [35.75 10.75 22.25 24.25]]
(5, 4)


### 4.4 練習問題

**問1**\
(1) 0~99までの100個の連続整数を値にもつ1次元の`np.ndarray`を作成し、shapeが`(10, 10)`の2次元配列となるように整形してください。\
(2) (1)の配列から偶数行目を抜き出したshapeが`(5, 10)`の2次元配列を作成してください。ただし行は0から数えます。\
(3) (1)の配列から奇数列目を抜き出したshapeが`(10, 5)`の2次元配列を作成してください。ただし列は0から数えます。\
(4) (1)の配列から、偶数行目かつ奇数列目にある値を要素にもつshapeが`(5, 5)`の2次元配列を作成してください。ただし行と列は0から数えます。

In [ ]:
# (1)
array1 = np.arange(0,100).reshape(10,10)
array1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
# (2)
idx1 = np.arange(0,array1.shape[0],2)
array1[idx1, :]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [ ]:
# (3)
idx2 = np.arange(1,array1.shape[1],2)
array1[:,idx2]

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [ ]:
#(4)
array1[np.ix_(idx1, idx2)]

array([[ 1,  3,  5,  7,  9],
       [21, 23, 25, 27, 29],
       [41, 43, 45, 47, 49],
       [61, 63, 65, 67, 69],
       [81, 83, 85, 87, 89]])

### 6.2 練習問題

**問1**\
(1) 1次元配列に対して、最大値のインデックスを取得する関数を自分で調べて、実行してください。\
(2) 2次元配列のaxis 1の方向で各最大値のインデックスを取得してください。その際次元を保持するようにして下さい。\
(3) 2次元配列の最大値のインデックスの場所が何行何列目かを取得する操作を自分で調べて実装してください。

In [ ]:
#(1)
#入力例
a = np.array([3, 8, 2, 6, 4, 4])
print(np.argmax(a))
# 出力例
# 1

#(2)
# 入力例
a = np.array([3, 8, 2, 6, 4, 4]).reshape(2, 3)
print(a)
print(np.argmax(a))
print(np.argmax(a, axis=1, keepdims=True))
print(np.expand_dims(np.argmax(a, axis=1), axis=1)) # 別解
# 出力例
# [[1],
#[0]]

#(3)
def toi3(a):
    max_value = np.min(a)
    ret = None
    for col in np.argmax(a, axis=1):
        for row in np.argmax(a, axis=0):
            if a[row,col] > max_value:
                max_value = a[row,col]
                ret = (row, col)
    return ret

# 入力例
a = np.array([3, 8, 2, 6, 4, 4]).reshape(2, 3)
print(f'最大値{np.max(a)}は{toi3(a)}成分にある。')
# 最大値8は(0, 1)成分にある
# 出力例
# (0, 1)

1
[[3 8 2]
 [6 4 4]]
1
[[1]
 [0]]
[[1]
 [0]]
最大値8は(np.int64(0), np.int64(1))成分にある。


***